### PR TITLE
ci: Build on windows

### PR DESCRIPTION
**Pull request by cameron-martin**
This requires a few hacks to avoid hitting the Windows path limit, plus a few generalisations around path names and usage of platform-specific extension traits.

### CODE REVIEW

**Comment by albertocavalcante** [comment]
Hey @cameron-martin, would like help on this one?

**Comment by cameron-martin** [comment]
Yes please. I believe the problem is that paths of certain files in the runfiles tree exceed the 260 character limit imposed by Windows. I fixed this for the rules_rust bzlmod examples in https://github.com/bazelbuild/rules_rust/pull/2454, but for some reason the paths here are still exceeding this limit. I'm yet to work out why this is, so help is very much appreciated.

**Comment by hauserx** [comment]
Added commit to fix failing tests under windows in https://github.com/cameron-martin/bazel-lsp/pull/55, feel free to cherry-pick that commit to this PR or close the other PR if not useful.

**Comment by cameron-martin** [comment]
Thanks. I've added your commit to this PR since I had to fix a rust-analyzer issue too. I'll close your PR, but thanks for fixing this issue!

**Comment by cameron-martin** [comment]
I believe this issue is fixed, but I've enabled a setting that should make builds public in #58.

**Pull request merged**
